### PR TITLE
feat: add support for piping json from stdin

### LINKED ISSUE #5: Feat: enable the CLI to receive Snyk's JSON input from stdin
## Description

In essence, `pie-my-vulns` uses the Snyk CLI behind the scenes to scan and use the JSON output of that to chart the vulnerabilities. If someone has the Snyk CLI already installed, they could do something like `snyk test --json | npx pie-my-vulns`. To enable that we should support getting the JSON input from stdin and also when that takes place there's no need to run the audit within `pie-my-vulns`'s own code.

### PR DESCRIPTION
**Pull request by rajkumaar23**
## Description

Add support for piping Snyk json from stdin

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

Closes #5 

## Motivation and Context

Allows the program to read Snyk JSON when piped

## How Has This Been Tested?

- All existing and new tests passed.
- Tested by running `snyk test --json | node bin/pie-my-vulns.js` and got same output as `node bin/pie-my-vulns.js`.

## Screenshots (if appropriate):

image

## Checklist:

- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I added a picture of a cute animal cause it's fun

image

### CODE REVIEW

**Comment by rajkumaar23** [comment]
@lirantal Let me know if there's any change required :)

**Comment by lirantal** [comment]
Looks really great @rajkumaar23 ✨

**Comment by lirantal** [comment]
@rajkumaar23 looks like end-to-end fail because of the missing file?
image

**Comment by lirantal** [comment]
@rajkumaar23 e2e tests probably run from the outer directory. Worth to use the path module in the test, and then refer to the current directory/or process.cwd() to then build the path to the `snyk.json` fixture. Can you apply the updates?

**Comment by lirantal** [comment]
interestingly enough, it works for the e2e_windows: 
image

**Comment by rajkumaar23** [comment]
Sure @lirantal

**Pull request merged**
