### PR TITLE
fix: set cwd for failing testcase

### PR DESCRIPTION
**Pull request by rajkumaar23**
## Description

This PR fixes a failing e2e test case due to wrong cwd.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

#29 

## Motivation and Context

It makes all the e2e ✅

## How Has This Been Tested?

By running `npm run test:e2e`

## Screenshots (if appropriate):
image

## Checklist:

- [ ] I have updated the documentation (if required).
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by rajkumaar23** [comment]
@lirantal This fixes the e2e testcase.
However, i’m just curious why you decided to remove e2e check action on PRs?

**Comment by lirantal** [comment]
e2e do run on PRs too but for some reason it didn't catch it, not entirely sure why

it did break on master before the actual e2e with a publish:
image

**Comment by lirantal** [comment]
Oh actually, it looks like CircleCI integration is missing here for some reason :-/ 
image

**Comment by lirantal** [comment]
Well, this won't work very well as the tests rely on an actual Snyk token to run. I'll merge for now and see how the master branch "takes it"

**Comment by lirantal** [comment]
@rajkumaar23 we'll have to take it PR by PR it seems :)

Failures from `test_windows` on master:

```
> pie-my-vulns@0.0.0-development test:e2e C:\Users\circleci\project
> jest -c jest.e2e.js

jest-haste-map: Haste module naming collision: project1
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>\__tests__\__e2e__\project1\package.json
    * <rootDir>\__tests__\__e2e__\project2\package.json

- Scanning project dependencies
✖ Scan failed

Unexpected failure: can't detect package manifest files
try running in the project's rootdir

To enable debug information invoke the CLI with a DEBUG=pie* prefix.

Please open an issue at: https://github.com/lirantal/pie-my-vulns/issues
cat: write error: No space left on device
FAIL __tests__/__e2e__/cli.e2e.js (26.143s)
  End-to-End CLI
    √ CLI should return error code 2 when vulnerabilities are found (4824ms)
    √ CLI should show vulnerabilities breakdown numbers and their titles (4612ms)
    √ CLI should return error code 1 when there is an issue (2726ms)
    √ CLI should return error code 0 when no vulnerabilities are found (4036ms)
    √ CLI should accept path to project directory from command argument (2986ms)
    × CLI should be able to read Snyk JSON from stdin (2254ms)

  ● End-to-End CLI › CLI should be able to read Snyk JSON from stdin

    expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: 1

      87 |       })
      88 |     } catch (err) {
    > 89 |       expect(err.status).toBe(2) // means that vulnerabilities were found
         |                          ^
      90 |     }
      91 |   })
      92 | })

      at Object.<anonymous> (__tests__/__e2e__/cli.e2e.js:89:26)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 5 passed, 6 total
Snapshots:   0 total
Time:        26.206s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pie-my-vulns@0.0.0-development test:e2e: `jest -c jest.e2e.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pie-my-vulns@0.0.0-development test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\circleci\AppData\Roaming\npm-cache\_logs\2020-10-01T08_16_56_827Z-debug.log

Exited with code exit status 1
```

**Comment by rajkumaar23** [comment]
@lirantal Looks like this is the main culprit `cat: write error: No space left on device`. I'm not sure how to fix that. I don't have Windows either. Any idea?

**Comment by lirantal** [comment]
Yes that's weird. No idea why it does that. Perhaps the shell there doesn't have "cat" or piping doesn't work?
@rajkumaar23 how about to workaround this for now we make that test only run on linux OS using the `os` module?

**Comment by rajkumaar23** [comment]
cool, that will work 👍 @lirantal

**Pull request merged**
