### PR TITLE
feat: show total number vulnerabilities found

### PR DESCRIPTION
**Pull request by dkorn**
## Description

Display the total number of vulnerabilities found in the project

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

Resolves: https://github.com/lirantal/pie-my-vulns/issues/4

## Motivation and Context

Gives the user additional info - the total number of vulnerabilities.

## How Has This Been Tested?

- Tested locally.
- Added the new title to the relevant e2e test

## Screenshots (if appropriate):
Screen Shot 2020-03-16 at 19 51 37

## Checklist:

- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by lirantal** [comment]
Looks great @dkorn 👏 
I'm thinking we should put that total summary in the bottom instead of the top so it can be a nice summary. What do you think?

**Comment by dkorn** [comment]
> I'm thinking we should put that total summary in the bottom instead of the top so it can be a nice summary. What do you think?

I completely agree 👍 
The total summary isn't the main focus of this tool (at least at the moment). Moving to the bottom.

**Comment by omeraha** [comment]
@dkorn Looks good indeed. I agree it would be better to place the total number in the bottom, especially if we're planning to add more summary information in the future.

**Comment by dkorn** [comment]
@lirantal @omeraha Done.

If you have more ideas for interesting summary data I can add those as well.
Does average `cvssScore` has any value?

**Comment by lirantal** [comment]
Looks good!
Hmmm, the JSON output has information about the number of deps tested, how about we print that in the bottom as well?

**Pull request merged**
