### PR TITLE
fix: run pipe from stdin test only on linux

### PR DESCRIPTION
**Pull request by rajkumaar23**
## Description

This PR makes the testcase for piping Snyk JSON from stdin run only on linux OS.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

Related to #5 , https://github.com/lirantal/pie-my-vulns/pull/73#issuecomment-702356949

## Motivation and Context

It prevents the testcase from running on Windows, which causes the CI to fail.

## How Has This Been Tested?

`npm run test:e2e` on macOS and the test doesn't run.

## Screenshots (if appropriate):

image

## Checklist:

- [x] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by rajkumaar23** [comment]
@lirantal Good that you have added CircleCI for the PRs. However, I have literally no clue how this PR is causing the rest of the testcases to fail 😢

**Comment by lirantal** [comment]
I've got the CircleCI for it running here now: https://github.com/lirantal/pie-my-vulns/tree/rajkumaar23-pipe-from-stdin

**Comment by lirantal** [comment]
Ok CI looks good on a diff branch:

**Pull request merged**
